Allow call compare.py from any dir 2
Fix a bug, where compare.py expects that current directory is the
script's dir. This leads to bug in https://osci-jenkins-1.ci.fedoraproject.org/job/eln-periodic/

+ ./compare/compare.py rawhide eln
Traceback (most recent call last):
  File "./compare/compare.py", line 395, in <module>
    content = sorted(get_content())
  File "./compare/compare.py", line 273, in get_content
    exclude_packagelist = open("lists/exclude.txt").read().splitlines()
FileNotFoundError: [Errno 2] No such file or directory: 'lists/exclude.txt'

Signed-off-by: Andrei Stepanov <astepano@redhat.com>